# Build of the xkop ipk package for OpenWrt 23 and 24.
# See Dockerfile-apk - the prepared SDK image carries everything slow.
ARG SDK_IMAGE=ghcr.io/jedakaya/xkop-sdk-ipk:24.10.8
FROM ${SDK_IMAGE}

ARG XKOP_VERSION
ENV XKOP_VERSION=${XKOP_VERSION}

WORKDIR /builder

COPY ./xkop /builder/package/feeds/utilities/xkop

RUN make defconfig \
    && make package/xkop/compile -j1 V=s
